### ISSUE TITLE
Piepleine Execution Issue

### ISSUE THREAD

**Issue by jainsourabh2** [piEsposito/vertex-ai-tutorials#1]
I am submitting a pipeline to Vertex AI but the pipeline completes in 10 seconds and shows the status as Succeeded. When I go into the pipeline , node-info shows the status as cached. What should I do to make the pipeline work?

![image](https://user-images.githubusercontent.com/7837488/121772135-35e79d00-cb91-11eb-8a93-c62c078e386b.png)

**Comment by piEsposito** [comment]
So, the first time you executed it, Vertex AI saves the intermediary steps in cache so, if you re-run it, it won't charge you to run everything again. Try changin the pipeline name and the function names and code, then you will trigger it to run again.

**Comment by jainsourabh2** [comment]
Thanks. I disabled the cache and now it's working correctly.
